### ISSUE TITLE
directory.io down!

### ISSUE THREAD

**Issue by Zeeko22** [saracen/directory.io#12]
Directory.io has been down and cannot use it to search, since the transaction function the site seems to be very heavy to load, slow and cannot search long numbers!!!  What happent ?

**Comment by killyou007** [comment]
hi

no one trust him and never pay anything.
nothing useful, he will provide you password protected file.
and asks you more money again and again to unlock the file.
but never give you the password.
you can't do with that file.
he is a cheater. never trust him.
i am complaining to github and other websites.
please don't trust him and never pay anything.

Regards,
Killer King

**Comment by killyou007** [comment]
hi

no one trust him and never pay anything.
nothing useful, he will provide you password protected file.
and asks you more money again and again to unlock the file.
but never give you the password.
you can't do with that file.
he is a cheater. never trust him.
i am complaining to github and other websites.
please don't trust him and never pay anything.

Regards,
Killer King

**Comment by saracen** [comment]
The user @directoryio has nothing to do with this project. Don't try to buy anything from them. If you've been scammed, move on and stop spamming the issues of this project.
