### ISSUE TITLE
Regarding Password

### ISSUE THREAD

**Issue by killyou007** [saracen/directory.io#13]
hello

please provide me the password for zip file.
please try to understand me.
thanks in advance and waiting for your response asap...

Regards,
Killer King

**Comment by killyou007** [comment]
hello

please provide me the password for zip file.
please try to understand me.
thanks in advance and waiting for your response asap...

Regards,
Killer King

**Comment by killyou007** [comment]
hi

i paid what you asked.
please provide me the password for zip file.
hope you can understand.
thanks in advance and waiting for your response asap...

Regards,
Killer King

**Comment by killyou007** [comment]
hi

i paid what you asked.
please provide me the password for zip file.
hope you can understand.
thanks in advance and waiting for your response asap...

Regards,
Killer King

**Comment by killyou007** [comment]
hi

i paid what you asked.
please provide me the password for zip file.
hope you can understand.
thanks in advance and waiting for your response asap...

Regards,
Killer King

**Comment by killyou007** [comment]
hi

i paid what you asked.
please provide me the password for zip file.
hope you can understand.
thanks in advance and waiting for your response asap...

Regards,
Killer King

**Comment by killyou007** [comment]
hi

i paid what you asked.
please provide me the password for zip file.
hope you can understand.
thanks in advance and waiting for your response asap...

Regards,
Killer King

**Comment by killyou007** [comment]
hi

no one trust him and never pay anything.
nothing useful, he will provide you password protected file.
and asks you more money again and again to unlock the file.
but never give you the password.
you can't do with that file.
he is a cheater. never trust him.
i am complaining to github and other websites.
please don't trust him and never pay anything.

Regards,
Killer King

**Comment by killyou007** [comment]
hi

no one trust him and never pay anything.
nothing useful, he will provide you password protected file.
and asks you more money again and again to unlock the file.
but never give you the password.
you can't do with that file.
he is a cheater. never trust him.
i am complaining to github and other websites.
please don't trust him and never pay anything.

Regards,
Killer King

**Comment by Zeeko22** [comment]
Be aware if that file could contain virus please!!!

**Comment by killyou007** [comment]
might be, but unable to extract the zip file.

**Comment by saracen** [comment]
The user @directoryio has nothing to do with this project. Don't try to buy anything from them. If you've been scammed, move on and stop spamming the issues of this project.
