### ISSUE TITLE
Regarding password

### ISSUE THREAD

**Issue by killyou007** [saracen/directory.io#15]
hi

if he is not the part in your project, then how he shared directory.io code?
whatever it is i would like to take legal action regarding you and your project.
we will see what happens next? but i never give up.
will try as maximum as possible to de-promote you and your project.
do you think it's a joke? you know i already paid for the project.

Regard,
Killer King

**Comment by saracen** [comment]
Directory.io is open source. It's literally hosted on this website under the "Code" tab. Why would you pay somebody for it?

A user has registered the "directoryio" username and commented on this project. It has nothing to do with me.

Please stop opening issues here.
