### ISSUE TITLE
undefined: time.Until while trying to install dependencies

### ISSUE THREAD

**Issue by ghost** [saracen/directory.io#16]
i am trying to Install dependencies
and i got this., 

[root@btc tmp]# go get github.com/btcsuite/btcd
# github.com/btcsuite/btcd
/root/projects/src/src/github.com/btcsuite/btcd/server.go:1233: undefined: time.Until

**Comment by saracen** [comment]
You need to update your version of Go. `time.Until` was added in [1.8](https://golang.org/doc/go1.8#time).
