### ISSUE TITLE
does it require full blockchain downloaded ?

### ISSUE THREAD

**Issue by ghost** [saracen/directory.io#17]
i mean , for directory.io to work,

does it require whole blockchain downloaded ?
becuase while downloading dependencies, we need to download bitcoin core written in GO language. 

Thanks

**Comment by saracen** [comment]
No, it does not require the blockchain download.

It has a dependency on btcd, not Bitcoin Core. However, it only uses some btcd packages, it doesn't require you to run a btcd node.
