### ISSUE TITLE
http: Accept error: accept tcp [::]:80: accept4: too many open files; retrying in 1s

### ISSUE THREAD

**Issue by ghost** [saracen/directory.io#19]
2017/12/12 01:44:04 http: Accept error: accept tcp [::]:80: accept4: too many open files; retrying in 1s
2017/12/12 01:44:05 http: Accept error: accept tcp [::]:80: accept4: too many open files; retrying in 1s
2017/12/12 01:44:06 http: Accept error: accept tcp [::]:80: accept4: too many open files; retrying in 1s
2017/12/12 01:44:07 http: Accept error: accept tcp [::]:80: accept4: too many open files; retrying in 1s
2017/12/12 01:44:08 http: Accept error: accept tcp [::]:80: accept4: too many open files; retrying in 1s

**Comment by ghost** [comment]
since then i have increased ulimit nofile counts , will check if this issue comes again. but this says , i we should close the body 
https://stackoverflow.com/questions/37454236/net-http-server-too-many-open-files-error


edit: found this 

https://medium.com/@nate510/don-t-use-go-s-default-http-client-4804cb19f779


edit: found this 

> Because there's no Close method on an http.ResponseWriter.
ref: https://groups.google.com/forum/#!topic/golang-nuts/vdNhwoqZE_c

**Comment by ghost** [comment]
every page load, adds new FD 

```
[root@ ~]# ls -l /proc/19138/fd | wc -l
99
[root@ ~]# ls -l /proc/19138/fd | wc -l
99
[root@ ~]# ls -l /proc/19138/fd | wc -l
110
[root@ ~]# ls -l /proc/19138/fd | wc -l
121
[root@ ~]# ls -l /proc/19138/fd | wc -l
123
[root@ ~]# ls -l /proc/19138/fd | wc -l
123
[root@ ~]# ls -l /proc/19138/fd | wc -l
123
[root@ ~]# ls -l /proc/19138/fd | wc -l

```

looks like we definately gotta close http connections after serving data.

**Comment by ghost** [comment]
so far my ugly hack.,
crontab every hour 
pkill directory && cd /root; nohup go/bin/directory &

**Comment by saracen** [comment]
You should probably set decent timeout values for the HTTP server if you don't have something in front of this, like nginx.

Cloudflare have a good blog post about this and Go: https://blog.cloudflare.com/the-complete-guide-to-golang-net-http-timeouts/
