### ISSUE TITLE
Can you share the updated (with balance info) code?

### ISSUE THREAD

**Issue by killyou007** [saracen/directory.io#8]
hi

i would like to modify, of course want to integrate some other features.
will let you know more information later.
can you share the updated code, including balances info?
thanks in advance...

Regards,
K1LL3R K1NG

**Comment by EBTCoin** [comment]
Hi,

Saracen didn't make the site with balances, I did.

What features do you want added?

I don't want to share the source yet.

Thanks,
Jude

**Comment by Zeeko22** [comment]
hi. pls can anyone help to make directory.io with balances , i tryed for 3 days cannot succeed.. i love this project.. Big thanks to the creator!

**Comment by ciabutas** [comment]
@Zeeko22  me too i need some free bitcoins

**Comment by Zeeko22** [comment]
haha... well to find free bitcoins is not the goal ... it is to try finid and if so, to tell all that impossible is nothing... but here we need to have the luck on our side. BIG luck!

**Comment by saracen** [comment]
Maybe you can look at https://github.com/saracen/bitcoin-all-key-generator instead, which does the same thing directory.io does, but locally.

There's little point in displaying balances on directory.io.

**Comment by saracen** [comment]
I'm closing this issue because directory.io does not display balances.

**Comment by Zeeko22** [comment]
I got all-key generator alredy.. I see.. with all respect!

**Comment by directoryio** [comment]
I Sell directory io with balance and préfix address Check contact me to angerfist2016@gmail.com
